### ISSUE TITLE
JSON output is not able to be trained.

### ISSUE THREAD

**Issue by crossoveranx** [cdqa-suite/cdQA-annotator#35]
I create a SQUAD compatible dataset using a set of PDF documents. I then upload this to the annotator, however the downloaded annotation JSON is missing question ids? Is this a feature to be implemented?

**Comment by fmikaelian** [comment]
Hi @crossoveranx 

It is a known issue, I'll implement a fix over the weekend 😃 

If you cannot wait you can still add the question ids using @andrelmfarias python snippet (see https://github.com/cdqa-suite/cdQA/issues/253#issuecomment-531192394)
