### ISSUE TITLE
Issue with running vue serve on windows 

### ISSUE THREAD

**Issue by Andreymshor** [cdqa-suite/cdQA-annotator#37]
Hello, I am having an issue with running `vue serve` on my Windows machine. When I try to run it, I get an error saying I'm missing (parts of) `core-js`. I have tried to install `core-js` with `npm install core-js` from the `cdQA-annotator` directory and am still getting the same issue.

I'm on Node v 12.13.0 and npm 6.12.0.

Full error:

```
 ERROR  Failed to compile with 4 errors                                                                    9:40:29 PM

These dependencies were not found:

* core-js/library/fn/array/from in ../node_modules/bootstrap-vue/esm/utils/array.js
* core-js/library/fn/array/is-array in ../node_modules/bootstrap-vue/esm/utils/array.js
* core-js/library/fn/object/assign in ../node_modules/bootstrap-vue/esm/utils/object.js
* core-js/library/fn/object/is in ../node_modules/bootstrap-vue/esm/utils/object.js
```

It suggests I install these with `npm install --save core-js/library/fn/array/from [...]`,  but that didn't solve the issue either.

**Comment by andrelmfarias** [comment]
@fmikaelian any ideas on how to solve this?

**Comment by vedaanth** [comment]
I am facing the same issue in cdQA-annotator and cdQA-ui

**Comment by vedaanth** [comment]
![Screenshot from 2019-11-09 23-34-24](https://user-images.githubusercontent.com/47405741/68529009-d2104900-0349-11ea-99d6-0f4e8b2324dc.png)

**Comment by DEEPAvtu** [comment]
for require error: just do `npm install require`

**Comment by Tahsin-Mayeesha** [comment]
Facing Same Issue, Windows 10.

**Comment by svanschalkwyk** [comment]
On one machine I had to run it NOT from the src folder, but the parent.

**Comment by svanschalkwyk** [comment]
npm run serve from the parent folder, not src folder.

**Comment by shivanand3939** [comment]
> On one machine I had to run it NOT from the src folder, but the parent.

Yes it worked for me as well!..
