### ISSUE TITLE
http://localhost:8080/ not running after vue serve command

### ISSUE THREAD

**Issue by TobiKoledoye** [cdqa-suite/cdQA-annotator#39]
Please what can i do as touching the annotator command. The http://localhost:8080/ is not running after vue serve command. The expected annotator page did not come up. even after manually typing the http://localhost:8080/ link.

How do go about this?
Thanks

**Comment by andrelmfarias** [comment]
Hi,

Have you installed the dependecies with `npm install`?

I just tried to run the app on my local machine and it worked fine...

**Comment by TobiKoledoye** [comment]
Yes. I have installed all dependencies. Seems I'm missing something, still haven't figured it out tho.

**Comment by rsjain1978** [comment]
Command _vue serve_ requires a global addon to be installed. Please run _npm install -g @vue/cli-service-global_ and try again.

Alternatively, you could simply run _npm run serve_

good luck !
