### ISSUE TITLE
"Next" Button doesn't work 

### ISSUE THREAD

**Issue by zick2** [cdqa-suite/cdQA-annotator#46]
My dataset had 3 sets of data, each set having one paragraph and context. When I upload the JSON file into the annotator the "Next" button only works on the first click, but the second click causes an error:  [Vue warn]: Error in render: "TypeError: Cannot read property 'context' of undefined"

**Comment by arefeh-k** [comment]
Hi,
I have the same problem, 
haven't you found any solution for it?

**Comment by zick2** [comment]
Unfortunately no.

**Comment by zick2** [comment]
I thought it should be fixed by now.
